project:
  type: book
  output-dir: _book

lang: es

book:
  title: "Comunicaciones"
  author: "VuelaLibre.net"
  chapters:
    - index.qmd
    - colofon.qmd
    - dedicatoria.qmd
    - prefacio.qmd
    - indice-ilustraciones.qmd
    - cap01-definiciones-y-técnica-de-comunicación.qmd
    - cap02-comunicaciones-vfr-en-aeródromos-no-controlados.qmd
    - cap03-comunicaciones-vfr-en-aeródromos-controlados.qmd
    - cap04-comunicaciones-vfr-con-atc-en-ruta.qmd
    - cap05-procedimientos-operativos-generales.qmd
    - cap06-términos-de-información-meteorológica-relevantes-para-vfr.qmd
    - cap07-acciones-ante-fallo-de-comunicaciones.qmd
    - cap08-procedimientos-de-socorro-y-urgencia.qmd
    - cap09-principios-generales-de-propagación-vhf-y-asignación-de-frecuencias.qmd
  appendices:
    - apendice-syllabus-oficial-easa---comunicaciones.qmd
    - apendice-códigos-q-esenciales-para-el-piloto-de-planeador.qmd
    - glosario.qmd
    - bibliografia.qmd

format:
  typst:
    toc: true
    number-sections: true
    keep-typ: true
    margin:
      top: 2.5cm
      bottom: 2.5cm
  epub:
    toc: true
