project:
  type: book
  output-dir: _book

book:
  title: "Planificación y Rendimiento de Vuelo"
  author: "VuelaLibre.net"
  chapters:
    - index.qmd
    - colofon.qmd
    - dedicatoria.qmd
    - prefacio.qmd
    - indice-ilustraciones.qmd
    - cap01-masa-y-centro-de-gravedad.qmd
    - cap02-polar-de-velocidades-de-planeadores-o-velocidad-de-crucero.qmd
    - cap03-planificación-de-vuelo-y-definición-de-tareas.qmd
    - cap04-plan-de-vuelo-icao.qmd
    - cap05-monitoreo-del-vuelo-y-replanificación-en-vuelo.qmd
  appendices:
    - apendice-syllabus-oficial-easa---planificación-y-rendimiento-de-vuelo.qmd
    - glosario.qmd
    - bibliografia.qmd

format:
  typst:
    toc: true
    number-sections: true
    keep-typ: true
    margin:
      top: 2.5cm
      bottom: 2.5cm
      left: 3cm
      right: 3cm
  epub:
    toc: true
