project:
  type: book
  output-dir: _book

lang: es
version: "0.8.1"
repo-url: "https://github.com/VuelaLibre-net/teoria-licencia-SPL"

book:
  title: "Planificación y Rendimiento de Vuelo"
  author: "VuelaLibre.net"
  chapters:
    - index.qmd
    - licencia.qmd
    - dedicatoria.qmd
    - epigrafe.qmd
    - reconocimientos.qmd
    - introduccion.qmd
    - cap01-masa-y-centro-de-gravedad.qmd
    - cap02-polar-de-velocidades-de-planeadores-o-velocidad-de-crucero.qmd
    - cap03-planificación-de-vuelo-y-definición-de-tareas.qmd
    - cap04-plan-de-vuelo-icao.qmd
    - cap05-monitoreo-del-vuelo-y-replanificación-en-vuelo.qmd
  appendices:
    - apendice-syllabus-oficial-easa---planificación-y-rendimiento-de-vuelo.qmd
    - glosario.qmd
    - bibliografia.qmd
    - colofon.qmd

format:
  orange-book-es-typst:
    toc: true
    number-sections: true
    keep-typ: true
    margin:
      top: 2.5cm
      bottom: 2.5cm
  epub:
    toc: true
