project:
  type: book
  output-dir: _book

lang: es

book:
  title: "Conocimientos Generales de la Aeronave"
  author: "VuelaLibre.net"
  chapters:
    - index.qmd
    - colofon.qmd
    - dedicatoria.qmd
    - prefacio.qmd
    - indice-ilustraciones.qmd
    - cap01-estructura.qmd
    - cap02-diseño-de-sistemas-cargas-y-tensiones.qmd
    - cap03-tren-de-aterrizaje-ruedas-neumáticos-y-frenos.qmd
    - cap04-masa-y-centro-de-gravedad.qmd
    - cap05-mandos-de-vuelo.qmd
    - cap06-instrumentos.qmd
    - cap07-montaje-de-la-aeronave-conexión-de-superficies-de-control.qmd
    - cap08-manuales-y-documentos.qmd
    - cap09-aeronavegabilidad-y-mantenimiento.qmd
    - cap10-estructura-motores-y-hélices.qmd
    - cap11-sistemas-de-lastre-con-agua.qmd
    - cap12-baterías.qmd
    - cap13-paracaídas-de-emergencia.qmd
    - cap14-equipo-de-evacuación-de-emergencia.qmd
  appendices:
    - apendice-syllabus-oficial-easa---conocimientos-generales-de-la-aeronave.qmd
    - glosario.qmd
    - bibliografia.qmd

format:
  typst:
    toc: true
    number-sections: true
    keep-typ: true
    margin:
      top: 2.5cm
      bottom: 2.5cm
      left: 3cm
      right: 3cm
  epub:
    toc: true
