project:
  type: book
  output-dir: _book

book:
  title: "Navegación"
  author: "VuelaLibre.net"
  chapters:
    - index.qmd
    - colofon.qmd
    - dedicatoria.qmd
    - prefacio.qmd
    - indice-ilustraciones.qmd
    - cap01-fundamentos-de-navegación.qmd
    - cap02-magnetismo-y-brújulas.qmd
    - cap03-cartas-aeronáuticas.qmd
    - cap04-navegación-por-estima.qmd
    - cap05-navegación-en-vuelo.qmd
    - cap06-uso-de-gnss.qmd
    - cap07-uso-de-ats.qmd
  appendices:
    - apendice-syllabus-oficial-easa---navegación.qmd
    - glosario.qmd
    - bibliografia.qmd

format:
  typst:
    toc: true
    number-sections: true
    margin:
      top: 2.5cm
      bottom: 2.5cm
      left: 3cm
      right: 3cm
  epub:
    toc: true
