project:
  type: book
  output-dir: _book

lang: es

book:
  title: "Factores Humanos"
  author: "VuelaLibre.net"
  chapters:
    - index.qmd
    - colofon.qmd
    - dedicatoria.qmd
    - prefacio.qmd
    - indice-ilustraciones.qmd
    - cap01-factores-humanos-conceptos-básicos.qmd
    - cap02-fisiología-aeronáutica-básica-y-mantenimiento-de-salud.qmd
    - cap03-psicología-aeronáutica-básica.qmd
    - cap04-uso-de-oxígeno.qmd
  appendices:
    - apendice-syllabus-oficial-easa---factores-humanos.qmd
    - glosario.qmd
    - bibliografia.qmd

format:
  orange-book-es-typst:
    toc: true
    number-sections: true
    keep-typ: true
    margin:
      top: 2.5cm
      bottom: 2.5cm
  epub:
    toc: true
