project:
  type: book
  output-dir: _book

lang: es

book:
  title: "Procedimientos Operativos"
  author: "VuelaLibre.net"
  chapters:
    - index.qmd
    - colofon.qmd
    - dedicatoria.qmd
    - prefacio.qmd
    - indice-ilustraciones.qmd
    - cap01-requisitos-generales.qmd
    - cap02-métodos-de-lanzamiento.qmd
    - cap03-técnicas-de-planeo.qmd
    - cap04-circuitos-y-aterrizaje.qmd
    - cap05-aterrizaje-fuera-de-campo-.qmd
    - cap06-procedimientos-operativos-especiales-y-peligros.qmd
    - cap07-procedimientos-de-emergencia.qmd
    - cap08-uso-y-aterrizaje-con-paracaídas-de-emergencia.qmd
  appendices:
    - apendice-syllabus-oficial-easa---procedimientos-operativos.qmd
    - glosario.qmd
    - bibliografia.qmd

format:
  typst:
    toc: true
    number-sections: true
    keep-typ: true
    margin:
      top: 2.5cm
      bottom: 2.5cm
      left: 3cm
      right: 3cm
  epub:
    toc: true
