project:
  type: book
  output-dir: _book

lang: es
version: "0.8.1"
repo-url: "https://github.com/VuelaLibre-net/teoria-licencia-SPL"

book:
  title: "Procedimientos Operativos"
  author: "VuelaLibre.net"
  chapters:
    - index.qmd
    - licencia.qmd
    - dedicatoria.qmd
    - epigrafe.qmd
    - reconocimientos.qmd
    - introduccion.qmd
    - cap01-requisitos-generales.qmd
    - cap02-métodos-de-lanzamiento.qmd
    - cap03-técnicas-de-planeo.qmd
    - cap04-circuitos-y-aterrizaje.qmd
    - cap05-aterrizaje-fuera-de-campo-.qmd
    - cap06-procedimientos-operativos-especiales-y-peligros.qmd
    - cap07-procedimientos-de-emergencia.qmd
    - cap08-uso-y-aterrizaje-con-paracaídas-de-emergencia.qmd
  appendices:
    - apendice-syllabus-oficial-easa---procedimientos-operativos.qmd
    - glosario.qmd
    - bibliografia.qmd
    - colofon.qmd

format:
  orange-book-es-typst:
    toc: true
    number-sections: true
    keep-typ: true
    margin:
      top: 2.5cm
      bottom: 2.5cm
  epub:
    toc: true
    include-in-header: _extensions/orange-book-es/epub-estilos.html
