project:
  type: book
  output-dir: _book

lang: es
version: "1.0.5"
repo-url: "https://github.com/VuelaLibre-net/teoria-licencia-SPL"
cubierta: "cover/frente.jpg"
contracubierta: "cover/reverso.jpg"

book:
  title: "Derecho Aéreo y Procedimientos de Control de Tránsito Aéreo"
  author: "VuelaLibre.net"
  chapters:
    - index.qmd
    - licencia.qmd
    - dedicatoria.qmd
    - epigrafe.qmd
    - reconocimientos.qmd
    - introduccion.qmd
    - cap01-derecho-internacional-convenios-acuerdos-y-organizaciones.qmd
    - cap02-aeronavegabilidad.qmd
    - cap03-marcas-de-nacionalidad-y-matrícula-de-aeronaves.qmd
    - cap04-licencias-de-personal.qmd
    - cap05-reglas-del-aire.qmd
    - cap06-procedimientos-para-navegación-aérea-operaciones-de-aeronaves.qmd
    - cap07-reglamentación-de-tránsito-aéreo-estructura-del-espacio-aéreo.qmd
    - cap08-servicio-de-tránsito-aéreo-.qmd
    - cap09-servicios-de-información-aeronáutica-ais.qmd
    - cap10-aeródromos-y-campos-de-despegue-externos.qmd
    - cap11-búsqueda-y-salvamento.qmd
    - cap12-seguridad.qmd
    - cap13-notificación-de-accidentes.qmd
    - cap14-derecho-nacional.qmd
  appendices:
    - apendice-syllabus-oficial-easa---derecho-aéreo.qmd
    - glosario.qmd
    - bibliografia.qmd
    - colofon.qmd
    - contracubierta.qmd

format:
  orange-book-es-typst:
    toc: true
    number-sections: true
    keep-typ: true
    margin:
      top: 2.5cm
      bottom: 2.5cm
  epub:
    toc: true
    epub-cover-image: cover/frente.jpg
    include-in-header: _extensions/orange-book-es/epub-estilos.html
