project:
  type: book
  output-dir: _book

lang: es

book:
  title: "Meteorología"
  author: "VuelaLibre.net"
  chapters:
    - index.qmd
    - dedicatoria.qmd
    - reconocimientos.qmd
    - introduccion.qmd
    - cap01-la-atmósfera.qmd
    - cap02-viento.qmd
    - cap03-termodinámica.qmd
    - cap04-nubes-y-niebla.qmd
    - cap05-precipitación.qmd
    - cap06-masas-de-aire-y-frentes.qmd
    - cap07-sistemas-de-presión.qmd
    - cap08-climatología.qmd
    - cap09-peligros-para-el-vuelo.qmd
    - cap10-información-meteorológica.qmd
  appendices:
    - apendice-syllabus-oficial-easa---meteorología.qmd
    - glosario.qmd
    - bibliografia.qmd
    - colofon.qmd

format:
  orange-book-es-typst:
    toc: true
    number-sections: true
    keep-typ: true
    margin:
      top: 2.5cm
      bottom: 2.5cm
  epub:
    toc: true
