project:
  type: book
  output-dir: _book

lang: es
version: "0.8.1"
repo-url: "https://github.com/VuelaLibre-net/teoria-licencia-SPL"

book:
  title: "Principios de Vuelo"
  author: "VuelaLibre.net"
  chapters:
    - index.qmd
    - licencia.qmd
    - dedicatoria.qmd
    - epigrafe.qmd
    - reconocimientos.qmd
    - introduccion.qmd
    - cap01-aerodinámica-flujo-de-aire.qmd
    - cap02-mecánica-de-vuelo.qmd
    - cap03-estabilidad.qmd
    - cap04-control.qmd
    - cap05-limitaciones-factor-de-carga-y-maniobras.qmd
    - cap06-pérdida-de-sustentación-y-autorrotación.qmd
    - cap07-picado-en-espiral.qmd
  appendices:
    - apendice-syllabus-oficial-easa---principios-de-vuelo.qmd
    - glosario.qmd
    - bibliografia.qmd
    - colofon.qmd

format:
  orange-book-es-typst:
    toc: true
    number-sections: true
    keep-typ: true
    margin:
      top: 2.5cm
      bottom: 2.5cm
  epub:
    toc: true
