project:
  type: book
  output-dir: _book

lang: es

book:
  title: "Principios de Vuelo"
  author: "VuelaLibre.net"
  chapters:
    - index.qmd
    - colofon.qmd
    - dedicatoria.qmd
    - prefacio.qmd
    - indice-ilustraciones.qmd
    - cap01-aerodinámica-flujo-de-aire.qmd
    - cap02-mecánica-de-vuelo.qmd
    - cap03-estabilidad.qmd
    - cap04-control.qmd
    - cap05-limitaciones-factor-de-carga-y-maniobras.qmd
    - cap06-pérdida-de-sustentación-y-autorrotación.qmd
    - cap07-picado-en-espiral.qmd
  appendices:
    - apendice-syllabus-oficial-easa---principios-de-vuelo.qmd
    - glosario.qmd
    - bibliografia.qmd

format:
  typst:
    toc: true
    number-sections: true
    keep-typ: true
    margin:
      top: 2.5cm
      bottom: 2.5cm
      left: 3cm
      right: 3cm
  epub:
    toc: true
